language: python
sudo: false
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - coverage run --branch --source . test.py
  - coverage run --append --branch --source . -m doctest examples.rst
after_success:
  - coveralls
