language: python
sudo: false
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - python data_test.py
  - python morphgnt_generate.py 1 2 3 4 9 23 24 25
  - python -m doctest examples.rst
  - coverage run --branch --source=accent.py,fileformat.py,greek_inflexion.py test.py
after_success:
  - coveralls
