language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 .
  - python test.py
  - python data_test.py
  - python -m doctest examples.rst
  - python morphgnt_generate.py 1 2 3 4 5 6 7 9 10 11 12 13 14 15 16 17 18 19 20 23 24 25 26 27
  - python homer_generate.py
